from dataclasses import dataclass


class Shape:
    def draw(self, surface, canvas): ...
    def update_canvas(self, surface, canvas): ...
    def move(self, dx, dy): ...
    def handles(self): ...
    def apply_handle(self, kind, x, y): ...
    def params_text(self): ...
    def set_params_text(self, txt): ...
    def to_dict(self): ...
    def bbox(self): ...


class OidMixin:
    _OID_COUNTER = 1

    def _new_oid(self):
        oid = f"oid:{OidMixin._OID_COUNTER}"
        OidMixin._OID_COUNTER += 1
        return oid
